---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	interpreter(interpreter)
	retriever(retriever)
	reasoner(reasoner)
	validator(validator)
	calculation_planner(calculation_planner)
	retry_search(retry_search)
	reinterpret_question(reinterpret_question)
	supervisor(supervisor)
	answer_regeneration(answer_regeneration)
	clarify(clarify)
	unanswerable(unanswerable)
	fail_closed(fail_closed)
	__end__([<p>__end__</p>]):::last
	__start__ --> interpreter;
	answer_regeneration --> validator;
	calculation_planner --> supervisor;
	clarify --> validator;
	fail_closed --> validator;
	interpreter --> supervisor;
	reasoner --> supervisor;
	retriever --> supervisor;
	retry_search --> retriever;
	reinterpret_question --> supervisor;
	supervisor -.-> __end__;
	supervisor -.-> answer_regeneration;
	supervisor -.-> calculation_planner;
	supervisor -.-> clarify;
	supervisor -.-> fail_closed;
	supervisor -.-> reasoner;
	supervisor -.-> retriever;
	supervisor -.-> retry_search;
	supervisor -.-> reinterpret_question;
	supervisor -.-> unanswerable;
	supervisor -.-> validator;
	unanswerable --> validator;
	validator --> supervisor;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
